name: Guidewire PR Trigger

on:
  workflow_dispatch:
    inputs:
      sourceBranch:
        required: true
        type: string
      targetBranch:
        required: true
        type: string
      prLink:
        required: true
        type: string
      prTitle:
        required: true
        type: string
      actorEmail:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Source Branch: ${{ github.event.inputs.sourceBranch }}"
          echo "Target Branch: ${{ github.event.inputs.targetBranch }}"
          echo "PR Link: ${{ github.event.inputs.prLink }}"
          echo "PR Title: ${{ github.event.inputs.prTitle }}"
          echo "Actor Email: ${{ github.event.inputs.actorEmail }}"
